### ISSUE TITLE
software-stack/lab: Python ltrace on docker

### ISSUE THREAD

**Issue by radudum10** [open-education-hub/operating-systems#183]
```shell
🐳 student@os:~/.../lab/support/high-level-lang$ ltrace -l 'libc*' python hello.py 2> libc.out
🐳 student@os:~/.../lab/support/high-level-lang$ wc -l libc.out 
0 libc.out
🐳 student@os:~/.../lab/support/high-level-lang$ ltrace -l 'libc*' python3 hello.py 2> libc.out
Hello, world!
🐳 student@os:~/.../lab/support/high-level-lang$ wc -l libc.out 
71 libc.out
🐳 student@os:~/.../lab/support/high-level-lang$ strace python3 hello.py 2> syscall.out 
Hello, world!
🐳 student@os:~/.../lab/support/high-level-lang$ wc -l syscall.out 
544 syscall.out
```
On docker, the number returned by wc is 71 which is a lot smaller than 50k :smile:.
Is this normal when using docker or is it an issue within the container?

**Comment by Alex-deVis** [comment]
Please provide the output from the host to get the whole picture.

**Comment by teodutu** [comment]
It could be that the container uses a more lightweight Python interpreter. Can you also paste the output of `pyton3 --version` and `/lib/x86_64-linux-gnu/libc.so.6` on both the container and your host system?

**Comment by radudum10** [comment]
> Please provide the output from the host to get the whole picture.
```shell
high-level-lang@(master): ltrace -l 'libc*' python hello.py 2> libc.out
Hello, world!
high-level-lang@(master): wc -l libc.out 
90048 libc.out
high-level-lang@(master): strace python hello.py 2> syscall.out
Hello, world!
high-level-lang@(master): wc -l syscall.out 
610 syscall.out
```

**Comment by radudum10** [comment]
> It could be that the container uses a more lightweight Python interpreter. Can you also paste the output of `pyton3 --version` and `/lib/x86_64-linux-gnu/libc.so.6` on both the container and your host system?

container:
```shell
🐳 student@os:~$ python --version
Python 3.8.10
🐳 student@os:~$ /lib/x86_64-linux-gnu/libc.so.6 
GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.9) stable release version 2.31.
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 9.4.0.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<https://bugs.launchpad.net/ubuntu/+source/glibc/+bugs>.
🐳 student@os:~$ 
```

host:
```shell
os-runner@(master): python --version
Python 3.11.1
os-runner@(master): /usr/lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.36.
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 12.2.1 20221121 (Red Hat 12.2.1-4).
libc ABIs: UNIQUE IFUNC ABSOLUTE
Minimum supported kernel: 3.2.0
For bug reporting instructions, please see:
<https://www.gnu.org/software/libc/bugs.html>.
```

**Comment by darius-m** [comment]
Out of curiosity, print the ltrace version and run  `ldd $(which python3)` on both systems. From the libc version it appears that you have a RedHat-based operating system (presumably Fedora) as the host, while the container is Ubuntu. The tool versions on the two operating systems are quite different, with Fedora going for closer to upstream versions for tools.

`ltrace` has been a source of some issues with unexpected outputs - see #27  for an example, but it is not the only possible issue. For example, statically linked binaries do not have to perform library calls, since the functions are present by default in the binary (to be precise, I don't think `ltrace` can detect them, since the dynamic linker is not invoked in any way). However, with python, the most likely cause is eager linking (it's compiled/linked with `-z now`), which makes older version of `ltrace` unable to detect library calls properly.

**Comment by darius-m** [comment]
Also, Fedora may have a different compilation default, as opposed to Ubuntu, where Ubuntu has `-z now` enabled by default and Fedora does not.

**Comment by radudum10** [comment]
> Also, Fedora may have a different compilation default, as opposed to Ubuntu, where Ubuntu has `-z now` enabled by default and Fedora does not.

host:
```shell
~@: ldd $(which python3)
	linux-vdso.so.1 (0x00007ffd38ffb000)
	libpython3.11.so.1.0 => /lib64/libpython3.11.so.1.0 (0x00007f2625800000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2625623000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f2625543000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2625db2000)
```
container:
```shell
🐳 student@os:~$ ldd $(which python3)
	linux-vdso.so.1 (0x00007ffe717f4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb284b0d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb284aea000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb284ae4000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fb284adf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb284990000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fb284962000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb284944000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb284d07000)
```

also on the [lab page](https://open-education-hub.github.io/operating-systems/Lab/Software%20Stack/High-Level%20Languages/content/high-level-lang) the output is `50469`

**Comment by darius-m** [comment]
The output from the lab page does not really reflect what you may see on every system. The expected output is closer to what the sample shows, and your issue is likely caused by the eager linker that is employed on the Ubuntu container. From the `ldd` output we can confirm that python is not statically linked, so that is not the reason.

@teodutu @razvand  Also considering the issue from last semester, it may be worth looking at alternatives to `ltrace` (e.g. `uftrace`, as mentioned in the issue #27). For now, the quickest approach would be using `ltrace -x '*'`, although it is known to print a lot of additional function calls inside the libraries. Not sure if filtering using a filter like `-x '*@plt'` would work.
