### ISSUE TITLE
Mutex vs Atomic

### ISSUE THREAD

**Issue by gabrielmocanu** [open-education-hub/operating-systems#33]
I think in this section [1] you should explain better this sentence.

```
So using the hardware support is more efficient, but it can only be leveraged for simple, individual instructions, such as loads and stores.
```

Hardware support is a bit unclear to me.
A good example is presented in this blog post [2]. That example with assembly-code explained very well the difference between Mutex and Atomic and what is with that hardware support.

[1]: https://open-education-hub.github.io/operating-systems/Lab/Compute/Synchronization/content/synchronization#atomics
[2]: https://coffeebeforearch.github.io/2020/08/04/atomic-vs-mutex.html

**Comment by teodutu** [comment]
There is a practice item that is precisely about handwritten assembly [in the Arena](https://open-education-hub.github.io/operating-systems/Lab/Compute/Arena/content/arena#atomic-assembly). I would keep it there as it's not _that_ important for the general flow of the lab. It is linked in the [Atomics section](https://open-education-hub.github.io/operating-systems/Lab/Compute/Synchronization/content/synchronization#atomics), so anyone who's interested can jump to it.

I think the section on atomic operations is better suited to explain that atomic operations are also available in high-level languages because of how important they are.

I improved the documentation in [this PR](https://github.com/open-education-hub/operating-systems/pull/35). Tell me if you think it's clear now.

**Comment by gabrielmocanu** [comment]
Fair enough.
