### ISSUE TITLE
app interact lab missing so cloud

### ISSUE THREAD

**Issue by Iustin-Ivan** [open-education-hub/operating-systems#85]

**Comment by teodutu** [comment]
Yup, we know. It's not missing, it's just incomplete. That's why it doesn't show up in the sidebar. I gave further details in this other issue on the same topic: https://github.com/open-education-hub/operating-systems/issues/79.

As general advice, it's good to provide a detailed description of the problem when creating an issue. In addition, check the existing issues (both open and closed) to see if your issue hasn't been brought up before.
